### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by papjul**
Untested, just translated straightforwardly

### CODE REVIEW

**Comment by f11894** [comment]
Thank you for your help in translating.
However, the description of the folder name in build-master.yml is still ko-KR.

**Comment by papjul** [comment]
Well spotted, thank you, it's fixed now.

**Comment by papjul** [comment]
@f11894 Is it possible to fix the width of the text of the button?
image

Or I can use lowercase if that's too complicated (I kept uppercase, just as in the English version):
image

**Comment by f11894** [comment]
I don't know if I can do it, but I'll work on it later.

**Pull request merged**
